drop table if exists public.answers cascade;

create table public.answers (
  idx bigint generated by default as identity primary key,
  love_ro text,
  money_ro text,
  daily_vibration_ro text,
  love_en text,
  money_en text,
  daily_vibration_en text,
  created_at timestamptz not null default now()
);

alter table public.answers enable row level security;

revoke all on table public.answers from anon, authenticated;
grant select on table public.answers to anon, authenticated;

drop policy if exists "Public read answers" on public.answers;

create policy "Public read answers"
on public.answers
for select
to anon, authenticated
using (true);

